networks:
  frontend:
    external: true
  backend:
    external: true

services:
  php:
#    image: 'php:fpm'
    build:
      context: ./data
      dockerfile: php.Dockerfile
    container_name: ${APP_NAME:?err}-php
    volumes:
      - './data/app:/var/www/html'
    depends_on:
      - mariadb
    networks:
      - backend

  nginx:
    image: nginx:latest
    container_name: ${APP_NAME:?err}-nginx
#    ports:
#      - '800:80'
#      - '4443:443'
    links:
      - 'php'
    volumes:
      - './data/app:/var/www/html'
      - './data:/etc/nginx/conf.d'
    networks:
      - backend
      - frontend

  mariadb:
    image: mariadb:latest
    container_name: ${APP_NAME:?err}-mariadb
    restart: 'always'
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:?err}
    volumes:
      - ./data
    networks:
      - backend