networks:
  frontend:
    external: true
  backend:
    external: true

services:
  php:
    # image: 'php:7.2-fpm'
    build:
      context: ./data
      dockerfile: php.Dockerfile
    container_name: ${APP_NAME:?err}-php
    volumes:
      - '/root/s-lemp/data/app:/var/www/html'
    depends_on:
      - mariadb

  nginx:
    image: nginx:latest
    container_name: ${APP_NAME:?err}-nginx
    ports:
      - '80:80'
      - '443:443'
    links:
      - 'php'
    volumes:
      - '/root/s-lemp/data/app:/var/www/html'
      - '/root/s-lemp/data:/etc/nginx/conf.d'

  mariadb:
    image: mariadb:latest
    container_name: ${APP_NAME:?err}-mariadb
    restart: 'always'
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:?err}
    volumes:
      - /root/s-lemp/data